[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Noto Sans"
FontSize=""

KeyboardSize="0.4"

RoundCorners="20"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/cyan_wallpaper.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.3"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#56b6c2"
DateTextColor="#56b6c2"
TimeTextColor="#56b6c2"

FormBackgroundColor="#1a1a1a"
BackgroundColor="#1a1a1a"
DimBackgroundColor="#0a0a0a"

LoginFieldBackgroundColor="#121212"
PasswordFieldBackgroundColor="#121212"
LoginFieldTextColor="#abb2bf"
PasswordFieldTextColor="#abb2bf"
UserIconColor="#56b6c2"
PasswordIconColor="#56b6c2"

PlaceholderTextColor="#5c6370"
WarningColor="#e06c75"

LoginButtonTextColor="#121212"
LoginButtonBackgroundColor="#56b6c2"
SystemButtonsIconsColor="#56b6c2"
SessionButtonTextColor="#56b6c2"
VirtualKeyboardButtonTextColor="#56b6c2"

DropdownTextColor="#abb2bf"
DropdownSelectedBackgroundColor="#56b6c2"
DropdownBackgroundColor="#1a1a1a"

HighlightTextColor="#121212"
HighlightBackgroundColor="#56b6c2"
HighlightBorderColor="#56b6c2"

HoverUserIconColor="#2a8a96"
HoverPasswordIconColor="#2a8a96"
HoverSystemButtonsIconsColor="#2a8a96"
HoverSessionButtonTextColor="#2a8a96"
HoverVirtualKeyboardButtonTextColor="#2a8a96"

#################### Form ####################

PartialBlur="true"
FullBlur="false"
BlurMax="100"
Blur="1.5"

HaveFormBackground="false"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
